version: "3.7"
services:

  server:
    build: ./server/
    networks:
      grpc-gateway:
        aliases:
          - backend

  gateway:
    build: ./
    volumes:
      - "./gateway/conf:/etc/nginx/conf.d"
    ports:
      - "9000:80"
    networks:
      - grpc-gateway

networks:
  grpc-gateway:
