version: 2.1
jobs:
  build:
    docker:
      - image: superpaintman/lua:5.1-luarocks
    steps:
      - checkout
      - run: luarocks install luaunit
      - run: luarocks install lua-protobuf
      - run: make test

  publish:
    docker:
      - image: superpaintman/lua:5.1-luarocks
    steps:
      - checkout
      - run:
          command: |
            VERSION=$(echo $CIRCLE_TAG | cut -c1-20)
            sed -i "s/<TAG>/$VERSION/g" ./lua-resty-gateway.rockspec
            luarocks pack lua-resty-gateway.rockspec
            luarocks upload lua-resty-gateway.rockspec --api-key=$LUAROCKS_API_KEY

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/




