version: 2.1
jobs:
  build:
    docker:
      - image: superpaintman/lua:5.1-luarocks
    steps:
      - checkout
      - run: luarocks install luaunit
      - run: luarocks install lua-protobuf
      - run: make test

  publish:
    docker:
      - image: superpaintman/lua:5.1-luarocks
    steps:
      - checkout
      - run:
          command: |
            apt-get update || true
            apt-get install -y zip
      - run:
          command: |
            VERSION=$(echo $CIRCLE_TAG | cut -c2-20)
            cp ./lua-resty-grpc-gateway.rockspec ./lua-resty-grpc-gateway-${VERSION}-1.rockspec
            sed -i "s/<TAG>/$VERSION/g" ./lua-resty-grpc-gateway-${VERSION}-1.rockspec
            luarocks pack lua-resty-grpc-gateway-${VERSION}-1.rockspec
            luarocks upload lua-resty-grpc-gateway-${VERSION}-1.rockspec --api-key=$LUAROCKS_API_KEY

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
      - publish:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*/




